version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  method-complexity:
    enabled: true
    config:
      threshold: 25
  method-lines:
    enabled: true
    config:
      threshold: 55
plugins:
  eslint:
    enabled: true
    channel: "eslint-6"
    config: .eslintrc_codeclimate.js
  fixme:
    enabled: true
exclude_patterns:
- "test/"
